<?php
/**
 * LUX ARCHIVE - Hostinger Static Edition
 * This script lists and provides a portal to the HTML blog posts generated by Zenith.
 */

// Configuration
$blog_title = "Digital Philosophy // Lux Archive";
$accent_color = "#ff4d4d"; // Revolution Red

// Get all HTML files, newest first
$files = glob("*.html");
usort($files, function ($a, $b) {
    return filemtime($b) - filemtime($a);
});
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo $blog_title; ?></title>
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600&family=Inter:wght@300;400;500&display=swap" rel="stylesheet">
    <style>
        :root {
            --bg: #050505;
            --surface: #0a0a0a;
            --accent: <?php echo $accent_color; ?>;
            --text: #ffffff;
            --text-dim: #666666;
            --card-bg: #111111;
        }

        body {
            background: var(--bg);
            color: var(--text);
            font-family: 'Inter', sans-serif;
            margin: 0;
            padding: 0;
            line-height: 1.6;
            -webkit-font-smoothing: antialiased;
        }

        .lux-header {
            padding: 2.5rem;
            border-bottom: 1px solid rgba(255,255,255,0.03);
            display: flex;
            justify-content: space-between;
            align-items: center;
            background: rgba(5,5,5,0.8);
            backdrop-filter: blur(10px);
            position: sticky;
            top: 0;
            z-index: 100;
        }

        .lux-logo {
            font-family: 'Outfit', sans-serif;
            font-weight: 600;
            font-size: 1.25rem;
            letter-spacing: 0.1em;
            text-decoration: none;
            color: var(--text);
            text-transform: uppercase;
        }

        .lux-logo span { color: var(--accent); }

        .container {
            max-width: 900px;
            margin: 0 auto;
            padding: 6rem 2rem;
        }

        .intro {
            margin-bottom: 5rem;
        }

        .intro h1 {
            font-family: 'Outfit', sans-serif;
            font-size: 4rem;
            font-weight: 600;
            line-height: 1;
            margin: 0 0 1.5rem 0;
            letter-spacing: -0.04em;
        }

        .intro p {
            color: var(--text-dim);
            font-size: 1.25rem;
            max-width: 500px;
        }

        .archive-grid {
            display: grid;
            gap: 1.5rem;
        }

        .blog-card {
            background: var(--card-bg);
            border: 1px solid rgba(255,255,255,0.05);
            padding: 2.5rem;
            border-radius: 4px; /* Brutalist sharp roundness */
            text-decoration: none;
            transition: all 0.4s cubic-bezier(0.16, 1, 0.3, 1);
            position: relative;
            overflow: hidden;
        }

        .blog-card:hover {
            border-color: var(--accent);
            transform: scale(1.02);
            background: #161616;
        }

        .blog-card .meta {
            font-size: 0.75rem;
            text-transform: uppercase;
            letter-spacing: 0.2em;
            color: var(--accent);
            margin-bottom: 1rem;
            display: block;
        }

        .blog-card h2 {
            margin: 0;
            font-family: 'Outfit', sans-serif;
            font-size: 1.5rem;
            font-weight: 500;
            color: var(--text);
            line-height: 1.3;
        }

        .footer {
            margin-top: 10rem;
            padding: 4rem 2.5rem;
            border-top: 1px solid rgba(255,255,255,0.03);
            text-align: center;
            color: var(--text-dim);
            font-size: 0.8rem;
            letter-spacing: 0.1em;
        }

        /* Ambient background glow */
        .glow {
            position: fixed;
            top: -10%;
            right: -10%;
            width: 50%;
            height: 50%;
            background: radial-gradient(circle, rgba(255,77,77,0.03) 0%, rgba(0,0,0,0) 70%);
            pointer-events: none;
            z-index: -1;
        }
    </style>
</head>
<body>
    <div class="glow"></div>

    <header class="lux-header">
        <a href="/" class="lux-logo">LUX<span>.</span>ARCHIVE</a>
        <div style="font-size: 0.7rem; color: var(--text-dim); letter-spacing: 0.2em;">INTELLIGENCE_REVOLUTION.SH</div>
    </header>

    <div class="container">
        <section class="intro">
            <h1>Beyond the <br>Screen.</h1>
            <p>The transmission digests of the Lux Engine. Pure philosophy, zero noise.</p>
        </section>

        <div class="archive-grid">
            <?php if (empty($files)): ?>
                <div style="padding: 4rem; border: 1px dashed rgba(255,255,255,0.1); text-align: center; color: var(--text-dim);">
                    The archive is currently silent. Synchronize Zenith to begin.
                </div>
            <?php
endif; ?>

            <?php foreach ($files as $file):
    $display_name = str_replace(['-', '.html'], [' ', ''], $file);
    $display_name = ucwords($display_name);
?>
                <a href="<?php echo $file; ?>" class="blog-card">
                    <span class="meta"><?php echo date("d M Y", filemtime($file)); ?></span>
                    <h2><?php echo $display_name; ?></h2>
                </a>
            <?php
endforeach; ?>
        </div>
    </div>

    <footer class="footer">
        POWERED BY LUX ENGINE // HOSTED VIA HOSTINGER // TRANSMITTED VIA ZENITH
    </footer>

    <!-- LUX CHAT WIDGET - Maintaining the connection to the Brain -->
    <script>
      window.LuxChatConfig = {
        siteId: 'companain-life',
        position: 'bottom-right',
        theme: 'dark',
        apiHost: 'https://lux-3er5.vercel.app' 
      };
    </script>
    <script src="https://lux-3er5.vercel.app/widget-loader.js" async></script>

</body>
</html>
